### ISSUE TITLE
Compile  "09_random_subdiv_remesh"  in Linux platform

### ISSUE THREAD

**Issue by HardingworkingRookie** [HTDerekLiu/surface_multigrid_code#2]
Hi, HTDerekLiu, thanks for your excellent job in "Neural Subdivision"; it inspires me a lot. And I want to generate some datasets for my jobs.
But when I compile the "09_random_subdiv_ remesh" following the steps you write in "readme.md", I met some problems.  Therefore, I want to ask you some questions.
1. It seems that your cpp program depends on "libigl". Which folder should we download the "libigl"to? Parallel to folder "09_random_subdiv_ remesh"? Or is it inside folder "09_random_subdiv_ remesh"?
2. I download the "libigl" inside the folder "09_random_subdiv_ remesh", and run "mkdir build" and "cd build". Then some errors occurred as follows:
`CMake Error at libigl/cmake/libigl.cmake:5 (message):
  You included libigl.cmake directly from your own project.  This behavior is
  not supported anymore.  Please add libigl to your project via
  add_subdirectory(<path_to_libigl>).  See the libigl example project for
  more information: https://github.com/libigl/libigl-example-project/
Call Stack (most recent call first):
  cmake/FindLIBIGL.cmake:33 (include)
  CMakeLists.txt:11 (find_package)`
I search for the solution about this error in Chrome, but I haven't found a solution. Could you give me some advice?

I don't have much experience with C++ code, so I would appreciate it if you could give me some advice.

**Comment by HardingworkingRookie** [comment]
I have solved the problem. The reason is that I forgot to clone this project recursively. After I used the command "git clone --recursively".  Two new problems occurred. And they can be solved with the solution in the following website.

[include could not find load file: libigl](https://github.com/libigl/libigl/issues/1098)
["__1" is not a member from "std"](https://github.com/HTDerekLiu/surface_multigrid_code/issues/1)

**Comment by HTDerekLiu** [comment]
That's great!! Thanks for sharing the solutions :)
